import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import GoogleLogin from 'react-google-login';
import React from 'react';

export default function Home() {
  
  let googleClientId=process.env.GOOGLE_CLIENT_ID||"";
  //사용자 정보를 담아둘 userObj
  const [userObj, setUserObj]=React.useState({
    email:"",
    name:""
  })
  //로그인 성공시 res처리
  const onLoginSuccess=(res)=>{
    setUserObj({...userObj,
      email:res.profileObj.email,
      name:res.profileObj.name
    })
    
  }
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Google Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GoogleLogin
        clientId = {googleClientId}
        buttonText="Google"
        onSuccess={result=>onLoginSuccess(result)}
        onFailure={result => console.log(result)}
      />

    </div>
  )
}
